/**
 * Constants for Gravure Rate Calculator.
 * Rates will be replaced by DB/backend values in a later phase.
 * All monetary values are in ₹.
 */

// ── Material display names (keyed by form field key) ─────────────────────
export const MATERIAL_NAMES = {
  polyester: "Polyester",
  silverPet: "Silver PET",
  ldRoll: "L.D. Roll",
  bopp: "B.O.P.P.",
};

// ── Printing ──────────────────────────────────────────────────────────────
export const NORMAL_COLOR_RATE = 5; // ₹ per color per kg of total material
export const METALLIC_COLOR_RATE = 8; // ₹ per metallic color per kg
export const MATT_FINISH_RATE = 3; // ₹ per kg

// ── Lamination ────────────────────────────────────────────────────────────
export const SINGLE_LAM_RATE = 12; // ₹ per kg
export const DOUBLE_LAM_RATE = 20; // ₹ per kg

// ── Slitting ──────────────────────────────────────────────────────────────
export const SLITTING_RATE = 4; // ₹ per kg

// ── Pouch rates by size string (₹ per kg) ────────────────────────────────
export const POUCH_RATE_BY_SIZE = {
  "4 x 6": 15,
  "5 x 7": 18,
  "6 x 8": 20,
  "7 x 10": 25,
};
export const DEFAULT_POUCH_RATE = 15; // fallback for unknown sizes

// ── Sample quotes (seed data — replace with DB fetch when backend is ready) ──
export const SAMPLE_QUOTES = [
  {
    id: "sample-1",
    savedAt: "2026-03-27T09:15:00.000Z",
    savedBy: "Arun",
    quoteName: "Rajesh Traders — 500g",
    pouchSize: "5x7",
    pricePerKg: 214.75,
    form: {
      quoteName: "Rajesh Traders — 500g",
      pouchSize: "5x7",
      materials: {
        polyester: { enabled: true, price: "220", micron: "12", qty: "2.4" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: true, price: "158", micron: "40", qty: "1.2" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "4",
      metallicColors: "0",
      mattFinish: false,
      lamination: "single",
      slitting: true,
      wastage: "3",
    },
  },
  {
    id: "sample-2",
    savedAt: "2026-03-24T14:30:00.000Z",
    savedBy: "Priya",
    quoteName: "Metro Snacks Order",
    pouchSize: "4x6",
    pricePerKg: 187.4,
    form: {
      quoteName: "Metro Snacks Order",
      pouchSize: "4x6",
      materials: {
        polyester: { enabled: true, price: "210", micron: "12", qty: "2.0" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "2",
      metallicColors: "0",
      mattFinish: false,
      lamination: "single",
      slitting: false,
      wastage: "2",
    },
  },
  {
    id: "sample-3",
    savedAt: "2026-03-20T11:00:00.000Z",
    savedBy: "Arun",
    quoteName: "Premium Masala Pack",
    pouchSize: "7x10",
    pricePerKg: 256.9,
    form: {
      quoteName: "Premium Masala Pack",
      pouchSize: "7x10",
      materials: {
        polyester: { enabled: true, price: "235", micron: "12", qty: "2.8" },
        silverPet: { enabled: true, price: "260", micron: "12", qty: "1.0" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "5",
      metallicColors: "2",
      mattFinish: true,
      lamination: "double",
      slitting: true,
      wastage: "5",
    },
  },
  {
    id: "sample-4",
    savedAt: "2026-03-15T08:45:00.000Z",
    savedBy: "Priya",
    quoteName: "Sunflower Seeds 250g",
    pouchSize: "4x6",
    pricePerKg: 198.2,
    form: {
      quoteName: "Sunflower Seeds 250g",
      pouchSize: "4x6",
      materials: {
        polyester: { enabled: true, price: "215", micron: "12", qty: "1.8" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: true, price: "170", micron: "20", qty: "1.0" },
      },
      normalColors: "3",
      metallicColors: "0",
      mattFinish: false,
      lamination: "single",
      slitting: false,
      wastage: "2",
    },
  },
  {
    id: "sample-5",
    savedAt: "2026-03-10T16:00:00.000Z",
    savedBy: "Arun",
    quoteName: "Agro Spices Export",
    pouchSize: "6x8",
    pricePerKg: 232.6,
    form: {
      quoteName: "Agro Spices Export",
      pouchSize: "6x8",
      materials: {
        polyester: { enabled: true, price: "225", micron: "12", qty: "2.5" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: true, price: "162", micron: "40", qty: "1.4" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "4",
      metallicColors: "1",
      mattFinish: false,
      lamination: "double",
      slitting: true,
      wastage: "3",
    },
  },
  {
    id: "sample-6",
    savedAt: "2026-02-26T10:20:00.000Z",
    savedBy: "Ravi",
    quoteName: "Chilli Flakes Retail",
    pouchSize: "5x7",
    pricePerKg: 209.15,
    form: {
      quoteName: "Chilli Flakes Retail",
      pouchSize: "5x7",
      materials: {
        polyester: { enabled: true, price: "218", micron: "12", qty: "2.2" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "3",
      metallicColors: "0",
      mattFinish: false,
      lamination: "single",
      slitting: true,
      wastage: "2",
    },
  },
  {
    id: "sample-7",
    savedAt: "2026-02-21T13:55:00.000Z",
    savedBy: "Arun",
    quoteName: "Nature Fresh Pouch",
    pouchSize: "7x10",
    pricePerKg: 271.3,
    form: {
      quoteName: "Nature Fresh Pouch",
      pouchSize: "7x10",
      materials: {
        polyester: { enabled: true, price: "240", micron: "12", qty: "2.6" },
        silverPet: { enabled: true, price: "270", micron: "12", qty: "0.8" },
        ldRoll: { enabled: true, price: "155", micron: "40", qty: "1.0" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "6",
      metallicColors: "2",
      mattFinish: true,
      lamination: "double",
      slitting: true,
      wastage: "5",
    },
  },
  {
    id: "sample-8",
    savedAt: "2026-02-16T09:00:00.000Z",
    savedBy: "Priya",
    quoteName: "Kerala Spice Mix",
    pouchSize: "4x6",
    pricePerKg: 183.5,
    form: {
      quoteName: "Kerala Spice Mix",
      pouchSize: "4x6",
      materials: {
        polyester: { enabled: true, price: "205", micron: "12", qty: "1.6" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: true, price: "165", micron: "20", qty: "0.9" },
      },
      normalColors: "2",
      metallicColors: "0",
      mattFinish: false,
      lamination: "single",
      slitting: false,
      wastage: "2",
    },
  },
  {
    id: "sample-9",
    savedAt: "2026-02-10T15:30:00.000Z",
    savedBy: "Ravi",
    quoteName: "Dry Fruit Premium",
    pouchSize: "6x8",
    pricePerKg: 244.8,
    form: {
      quoteName: "Dry Fruit Premium",
      pouchSize: "6x8",
      materials: {
        polyester: { enabled: true, price: "230", micron: "12", qty: "2.4" },
        silverPet: { enabled: true, price: "265", micron: "12", qty: "1.1" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "5",
      metallicColors: "1",
      mattFinish: false,
      lamination: "double",
      slitting: false,
      wastage: "3",
    },
  },
  {
    id: "sample-10",
    savedAt: "2026-02-04T11:10:00.000Z",
    savedBy: "Arun",
    quoteName: "Pickle Pouch 200g",
    pouchSize: "4x6",
    pricePerKg: 175.95,
    form: {
      quoteName: "Pickle Pouch 200g",
      pouchSize: "4x6",
      materials: {
        polyester: { enabled: true, price: "200", micron: "12", qty: "1.5" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: true, price: "150", micron: "40", qty: "0.8" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "2",
      metallicColors: "0",
      mattFinish: false,
      lamination: "single",
      slitting: false,
      wastage: "2",
    },
  },
  {
    id: "sample-11",
    savedAt: "2026-01-28T14:00:00.000Z",
    savedBy: "Priya",
    quoteName: "Turmeric Powder Pack",
    pouchSize: "5x7",
    pricePerKg: 218.4,
    form: {
      quoteName: "Turmeric Powder Pack",
      pouchSize: "5x7",
      materials: {
        polyester: { enabled: true, price: "222", micron: "12", qty: "2.0" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: true, price: "168", micron: "20", qty: "1.1" },
      },
      normalColors: "4",
      metallicColors: "0",
      mattFinish: false,
      lamination: "single",
      slitting: true,
      wastage: "3",
    },
  },
  {
    id: "sample-12",
    savedAt: "2026-01-22T09:30:00.000Z",
    savedBy: "Arun",
    quoteName: "Rice Brand Export",
    pouchSize: "7x10",
    pricePerKg: 263.7,
    form: {
      quoteName: "Rice Brand Export",
      pouchSize: "7x10",
      materials: {
        polyester: { enabled: true, price: "238", micron: "12", qty: "2.5" },
        silverPet: { enabled: true, price: "268", micron: "12", qty: "0.9" },
        ldRoll: { enabled: true, price: "160", micron: "40", qty: "1.2" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "5",
      metallicColors: "2",
      mattFinish: false,
      lamination: "double",
      slitting: true,
      wastage: "5",
    },
  },
  {
    id: "sample-13",
    savedAt: "2026-01-17T16:45:00.000Z",
    savedBy: "Ravi",
    quoteName: "Coffee Pouch Metallic",
    pouchSize: "6x8",
    pricePerKg: 295.2,
    form: {
      quoteName: "Coffee Pouch Metallic",
      pouchSize: "6x8",
      materials: {
        polyester: { enabled: true, price: "245", micron: "12", qty: "2.2" },
        silverPet: { enabled: true, price: "280", micron: "12", qty: "1.3" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "4",
      metallicColors: "3",
      mattFinish: true,
      lamination: "double",
      slitting: false,
      wastage: "5",
    },
  },
  {
    id: "sample-14",
    savedAt: "2026-01-11T10:00:00.000Z",
    savedBy: "Priya",
    quoteName: "Atta Pack 1kg",
    pouchSize: "7x10",
    pricePerKg: 192.6,
    form: {
      quoteName: "Atta Pack 1kg",
      pouchSize: "7x10",
      materials: {
        polyester: { enabled: true, price: "208", micron: "12", qty: "2.3" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: true, price: "152", micron: "40", qty: "1.4" },
        bopp: { enabled: true, price: "162", micron: "20", qty: "0.8" },
      },
      normalColors: "3",
      metallicColors: "0",
      mattFinish: false,
      lamination: "single",
      slitting: false,
      wastage: "2",
    },
  },
  {
    id: "sample-15",
    savedAt: "2026-01-05T13:15:00.000Z",
    savedBy: "Arun",
    quoteName: "Organic Jaggery 500g",
    pouchSize: "5x7",
    pricePerKg: 226.85,
    form: {
      quoteName: "Organic Jaggery 500g",
      pouchSize: "5x7",
      materials: {
        polyester: { enabled: true, price: "228", micron: "12", qty: "2.1" },
        silverPet: { enabled: true, price: "255", micron: "12", qty: "0.7" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "4",
      metallicColors: "1",
      mattFinish: false,
      lamination: "single",
      slitting: true,
      wastage: "3",
    },
  },
  {
    id: "sample-16",
    savedAt: "2025-12-28T08:50:00.000Z",
    savedBy: "Ravi",
    quoteName: "Coriander Seeds Bulk",
    pouchSize: "6x8",
    pricePerKg: 237.1,
    form: {
      quoteName: "Coriander Seeds Bulk",
      pouchSize: "6x8",
      materials: {
        polyester: { enabled: true, price: "232", micron: "12", qty: "2.4" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: true, price: "158", micron: "40", qty: "1.3" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "4",
      metallicColors: "1",
      mattFinish: false,
      lamination: "double",
      slitting: false,
      wastage: "3",
    },
  },
  {
    id: "sample-17",
    savedAt: "2025-12-22T15:20:00.000Z",
    savedBy: "Priya",
    quoteName: "Herbal Tea Blend",
    pouchSize: "4x6",
    pricePerKg: 281.5,
    form: {
      quoteName: "Herbal Tea Blend",
      pouchSize: "4x6",
      materials: {
        polyester: { enabled: true, price: "242", micron: "12", qty: "1.8" },
        silverPet: { enabled: true, price: "275", micron: "12", qty: "1.0" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "5",
      metallicColors: "2",
      mattFinish: true,
      lamination: "double",
      slitting: true,
      wastage: "5",
    },
  },
  {
    id: "sample-18",
    savedAt: "2025-12-16T11:40:00.000Z",
    savedBy: "Arun",
    quoteName: "Basmati Rice 2kg",
    pouchSize: "7x10",
    pricePerKg: 203.75,
    form: {
      quoteName: "Basmati Rice 2kg",
      pouchSize: "7x10",
      materials: {
        polyester: { enabled: true, price: "212", micron: "12", qty: "2.5" },
        silverPet: { enabled: false, price: "", micron: "", qty: "" },
        ldRoll: { enabled: true, price: "155", micron: "40", qty: "1.5" },
        bopp: { enabled: true, price: "165", micron: "20", qty: "0.9" },
      },
      normalColors: "3",
      metallicColors: "0",
      mattFinish: false,
      lamination: "single",
      slitting: true,
      wastage: "2",
    },
  },
  {
    id: "sample-19",
    savedAt: "2025-12-10T14:25:00.000Z",
    savedBy: "Ravi",
    quoteName: "Sesame Seeds Export",
    pouchSize: "5x7",
    pricePerKg: 248.3,
    form: {
      quoteName: "Sesame Seeds Export",
      pouchSize: "5x7",
      materials: {
        polyester: { enabled: true, price: "235", micron: "12", qty: "2.2" },
        silverPet: { enabled: true, price: "262", micron: "12", qty: "0.8" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: true, price: "172", micron: "20", qty: "0.9" },
      },
      normalColors: "5",
      metallicColors: "1",
      mattFinish: false,
      lamination: "double",
      slitting: false,
      wastage: "3",
    },
  },
  {
    id: "sample-20",
    savedAt: "2025-12-03T09:05:00.000Z",
    savedBy: "Priya",
    quoteName: "Cardamom Premium Grade",
    pouchSize: "4x6",
    pricePerKg: 312.9,
    form: {
      quoteName: "Cardamom Premium Grade",
      pouchSize: "4x6",
      materials: {
        polyester: { enabled: true, price: "250", micron: "12", qty: "1.7" },
        silverPet: { enabled: true, price: "285", micron: "12", qty: "1.2" },
        ldRoll: { enabled: false, price: "", micron: "", qty: "" },
        bopp: { enabled: false, price: "", micron: "", qty: "" },
      },
      normalColors: "6",
      metallicColors: "3",
      mattFinish: true,
      lamination: "double",
      slitting: true,
      wastage: "7",
    },
  },
];
